import 'package:flutter/cupertino.dart';

class Home_provider extends ChangeNotifier {
  List Images = [
    "assets/images/ss1.png",
    "assets/images/ss2.png",
    "assets/images/ss3.png",
    "assets/images/ss4.png",
    "assets/images/ss6.png",
    "assets/images/ss7.png",
    "assets/images/ss8.png",
    "assets/images/ss9.jpg",
    // "assets/images/ss1.png",
    // "assets/images/ss2.png",
    // "assets/images/ss8.png",
    // "assets/images/ss9.jpg",
    // "assets/images/ss3.png",
    // "assets/images/ss6.png",
    // "assets/images/ss7.png",
    // "assets/images/ss4.png",
    // "assets/images/ss1.png",
    // "assets/images/ss2.png",
    // "assets/images/ss3.png",
    // "assets/images/ss4.png",
    // "assets/images/ss6.png",
    // "assets/images/ss7.png",
    // "assets/images/ss8.png",
    // "assets/images/ss9.jpg",
    // "assets/images/ss1.png",
    // "assets/images/ss2.png",
    // "assets/images/ss8.png",
    // "assets/images/ss9.jpg",
    // "assets/images/ss3.png",
    // "assets/images/ss6.png",
    // "assets/images/ss7.png",
    // "assets/images/ss4.png",
  ];

  List Name = [
    "Qutub minar",
    "somnath temple",
    "kedarnath temple",
    "ajnata ",
    "goa",
    "maldives",
    "sun shine",
    "nature",
    // "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  //   "kedarnath temple",
  ];
}
